### ISSUE TITLE
Unable to sign in to YouTube++ (current and old versions)

### ISSUE THREAD

**Issue by therealFoxster** [therealFoxster/altsource#1]
When attempting to sign in to YouTube++ with a Google account, the action fails with the following error:

> **Couldn't sign you in**
> You can't sign in to this app because Google can't confirm that it's safe

**Comment by foxster-mp4** [comment]
For now, a workaround can be found [here](https://www.reddit.com/r/sideloaded/comments/wh0g35/how_to_sign_in_to_tweaked_google_app/?utm_source=share&utm_medium=web2x&context=3). 

A new version of the app is being worked on and will have the original bundle ID (com.google.ios.youtube) which should (hopefully) resolve this issue.
